CREATE TABLE DEPTT (
    DNO VARCHAR2(3) PRIMARY KEY CHECK (DNO LIKE 'D%'),
    DNAME VARCHAR2(10) UNIQUE
)

CREATE TABLE EMPP (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    EJOB VARCHAR2(9) DEFAULT 'CLRK' CHECK (EJOB IN ('CLRK', 'MGR', 'A.MGR', 'GM', 'CEO')),
    MGR_ID NUMBER(4),
    BIRTH_DATE DATE,
    SAL NUMBER(7,2) DEFAULT 20001 CHECK (SAL > 20000),
    COMM NUMBER(7,2) DEFAULT 1000,
    DEPTNO VARCHAR2(3) REFERENCES DEPTT(DNO),
    PRJ_ID VARCHAR2(5) DEFAULT 'CLRK' CONSTRAINT FK_PROJECT CHECK (PRJ_ID IN ('CLRK', 'MGR', 'A.MGR', 'GM', 'CEO')),
    DATE_OF_JOIN DATE,
    CONSTRAINT CHK_BIRTH_DATE CHECK (BIRTH_DATE < DATE_OF_JOIN)
)

ALTER TABLE EMPP 
ADD (
    CONSTRAINT PK_EMP PRIMARY KEY (EMPNO),
    CONSTRAINT FK_MGR FOREIGN KEY (MGR_ID) REFERENCES EMP(EMPNO)
)

ALTER TABLE EMPP
MODIFY PRJ_ID VARCHAR2(5)

ALTER TABLE EMPP DROP CONSTRAINT FK_PROJECT

ALTER TABLE EMPP
ADD CONSTRAINT FK_PROJECT FOREIGN KEY (DEPTNO, PRJ_ID) REFERENCES PROJECTS(DNO, PRJ_NO)

CREATE TABLE PROJECTS (
    DNO VARCHAR2(3) NOT NULL REFERENCES DEPTT(DNO),
    PRJ_NO VARCHAR2(5) NOT NULL CHECK (PRJ_NO LIKE 'P%'),
    PRJ_NAME VARCHAR2(10),
    PRJ_CREDITS NUMBER(2) CHECK (PRJ_CREDITS BETWEEN 1 AND 10),
    START_DATE DATE,
    END_DATE DATE,
    PRIMARY KEY (DNO, PRJ_NO),
    CHECK (END_DATE > START_DATE)
)

ALTER TABLE DEPTT 
ADD (
    LOCATIONS VARCHAR2(9) 
    DEFAULT 'BNG' 
    CONSTRAINT CHK_LOCATIONS 
    CHECK (LOCATIONS IN ('BNG', 'MNG', 'MUB', 'HYD', 'CHN'))
)



SELECT *
FROM DEPTT

SELECT *
FROM EMPP

SELECT *
FROM PROJECTS

SELECT *
FROM EMPP
WHERE SAL > 25000 OR DEPTNO IN 'D2'

SELECT * 
FROM DEPTT 
WHERE DNO = 'D5';

UPDATE PROJECTS 
SET DNO = 'D5'
WHERE DNO = 'D1' AND PRJ_NO = 'P1';

SELECT * 
FROM PROJECTS;

