CREATE TABLE DEPTT (
    DNO VARCHAR2(3) PRIMARY KEY CHECK (DNO LIKE 'D%'),
    DNAME VARCHAR2(10) UNIQUE
)

CREATE TABLE EMPP (
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    EJOB VARCHAR2(9) DEFAULT 'CLRK' CHECK (EJOB IN ('CLRK', 'MGR', 'A.MGR', 'GM', 'CEO')),
    MGR_ID NUMBER(4),
    BIRTH_DATE DATE,
    SAL NUMBER(7,2) DEFAULT 20001 CHECK (SAL > 20000),
    COMM NUMBER(7,2) DEFAULT 1000,
    DEPTNO VARCHAR2(3) REFERENCES DEPTT(DNO),
    PRJ_ID VARCHAR2(5) DEFAULT 'CLRK' CONSTRAINT FK_PROJECT CHECK (PRJ_ID IN ('CLRK', 'MGR', 'A.MGR', 'GM', 'CEO')),
    DATE_OF_JOIN DATE,
    CONSTRAINT CHK_BIRTH_DATE CHECK (BIRTH_DATE < DATE_OF_JOIN)
)

ALTER TABLE EMPP 
ADD (
    CONSTRAINT PK_EMP PRIMARY KEY (EMPNO),
    CONSTRAINT FK_MGR FOREIGN KEY (MGR_ID) REFERENCES EMP(EMPNO)
)

ALTER TABLE EMPP
MODIFY PRJ_ID VARCHAR2(5)

ALTER TABLE EMPP DROP CONSTRAINT FK_PROJECT

ALTER TABLE EMPP
ADD CONSTRAINT FK_PROJECT FOREIGN KEY (DEPTNO, PRJ_ID) REFERENCES PROJECTS(DNO, PRJ_NO)

CREATE TABLE PROJECTS (
    DNO VARCHAR2(3) NOT NULL REFERENCES DEPTT(DNO),
    PRJ_NO VARCHAR2(5) NOT NULL CHECK (PRJ_NO LIKE 'P%'),
    PRJ_NAME VARCHAR2(10),
    PRJ_CREDITS NUMBER(2) CHECK (PRJ_CREDITS BETWEEN 1 AND 10),
    START_DATE DATE,
    END_DATE DATE,
    PRIMARY KEY (DNO, PRJ_NO),
    CHECK (END_DATE > START_DATE)
)

ALTER TABLE DEPTT 
ADD (
    LOCATIONS VARCHAR2(9) 
    DEFAULT 'BNG' 
    CONSTRAINT CHK_LOCATIONS 
    CHECK (LOCATIONS IN ('BNG', 'MNG', 'MUB', 'HYD', 'CHN'))
)



-- ALTER TABLE EMP DROP CONSTRAINTS Check_PRJ_ID;
-- ALTER TABLE EMP MODIFY PRJ_ID DEFAULT NULL;







SELECT *
FROM DEPTT

SELECT *
FROM EMPP

SELECT *
FROM PROJECTS

SELECT *
FROM EMPP
WHERE SAL > 25000 OR DEPTNO IN 'D2'

SELECT * 
FROM DEPTT 
WHERE DNO = 'D5';

UPDATE EMPP 
SET DEPTNO = 'D5'
WHERE DEPTNO = 'D1' AND PRJ_ID = 'P1';

UPDATE PROJECTS 
SET DNO = 'D5'
WHERE DNO = 'D1' AND PRJ_NO = 'P1';

SELECT * 
FROM PROJECTS;

UPDATE EMPP 
SET EJOB = 'MGR', SAL = 35000, MGR_ID = 111 
WHERE EMPNO = 123;

SELECT ENAME, SAL 
FROM EMPP 
WHERE SAL BETWEEN 25200 AND 35200;

SELECT ENAME 
FROM EMPP
WHERE MGR_ID IN (100, 125, 150);

SELECT ENAME 
FROM EMPP 
WHERE ENAME LIKE 'M%' OR ENAME LIKE 'R%';

SELECT ENAME 
FROM EMPP
WHERE ENAME NOT LIKE 'M%';

SELECT 
    MIN(SAL) AS MIN_SALARY,
    MAX(SAL) AS MAX_SALARY,
    AVG(SAL) AS AVG_SALARY 
FROM EMPP;

SELECT DNO, PRJ_NO, COUNT(EMPNO) AS EMPLOYEE_COUNT
FROM PROJECTS JOIN EMPP
ON DNO = DEPTNO AND PRJ_NO = PRJ_ID
GROUP BY DNO, PRJ_NO;

SELECT 
    E.ENAME AS EMPLOYEE_NAME,
    M.ENAME AS MANAGER_NAME 
FROM EMPP E
LEFT JOIN EMPP M ON E.MGR_ID = M.EMPNO;

SELECT 
    E.ENAME,
    D.DNAME,
    P.PRJ_NAME 
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO
JOIN PROJECTS P ON E.DEPTNO = P.DNO AND E.PRJ_ID = P.PRJ_NO;

SELECT ENAME, SAL 
FROM EMPP 
WHERE ENAME LIKE 'Rvi%';















SELECT PRJ_NAME 
FROM PROJECTS 
WHERE DNO = (SELECT DNO FROM DEPTT WHERE DNAME = 'Marketing');

SELECT 
    SYSDATE AS CURRENT_DATE,
    53 AS "NUMBER",
    ABS(-45) AS ABSOLUTE_VALUE,
    TO_CHAR(SYSDATE, 'MON-YY') AS MONTH_YEAR 
FROM DUAL;

SELECT ENAME, SAL 
FROM EMPP 
ORDER BY SAL DESC;

SELECT D.DNAME 
FROM DEPTT D
JOIN PROJECTS P ON D.DNO = P.DNO 
GROUP BY D.DNAME 
HAVING COUNT(P.PRJ_NO) > 1;

SELECT D.DNAME, MAX(E.SAL) AS MAX_SALARY, MIN(E.SAL) AS MIN_SALARY 
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO 
GROUP BY D.DNAME;

SELECT ENAME 
FROM EMPP
WHERE (SYSDATE - DATE_OF_JOIN)/365 > 5;

SELECT 
    EMPNO, 
    ENAME, 
    FLOOR((SYSDATE - BIRTH_DATE)/365) AS AGE,
    (BIRTH_DATE + (60*365) + 15) AS RETIREMENT_DATE 
FROM EMPP;

SELECT ENAME 
FROM EMPP
WHERE EXTRACT(MONTH FROM BIRTH_DATE) = 12;

SELECT ENAME 
FROM EMPP
WHERE EXTRACT(YEAR FROM BIRTH_DATE) = 1980;

SELECT ENAME 
FROM EMPP
WHERE EXTRACT(DAY FROM DATE_OF_JOIN) = 12;

SELECT ENAME 
FROM EMPP
WHERE (SYSDATE - DATE_OF_JOIN)/365 > 10;

SELECT PRJ_NO, PRJ_NAME 
FROM PROJECTS 
WHERE (END_DATE - START_DATE)/365 > 1;

SELECT E.ENAME 
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO 
WHERE D.LOCATIONS IN ('BNG', 'MUB', 'HYD');

UPDATE EMPP
SET COMM = COMM + (SAL * 0.1);

SELECT 
    RPAD(ENAME, 30, '.') AS PADDED_NAME,
    P.PRJ_CREDITS 
FROM EMPP E
JOIN PROJECTS P ON E.DEPTNO = P.DNO AND E.PRJ_ID = P.PRJ_NO;

SELECT 
    REPLACE(INITCAP(ENAME), 'a', '$') AS FORMATTED_NAME 
FROM EMPP E
JOIN PROJECTS P ON E.DEPTNO = P.DNO AND E.PRJ_ID = P.PRJ_NO 
WHERE P.PRJ_CREDITS > 7;

SELECT D.DNAME, SUM(E.SAL) AS TOTAL_SALARY 
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO 
GROUP BY D.DNAME;








SELECT EJOB, SUM(SAL) AS TOTAL_SALARY
FROM EMPP
GROUP BY EJOB;

SELECT DEPTNO
FROM (
    SELECT DEPTNO, COUNT(EMPNO) AS EMP_COUNT
    FROM EMPP
    WHERE PRJ_ID = 'P1'
    GROUP BY DEPTNO
) 
WHERE EMP_COUNT = (
    SELECT MAX(EMP_COUNT)
    FROM (
        SELECT COUNT(EMPNO) AS EMP_COUNT
        FROM EMPP
        WHERE PRJ_ID = 'P1'
        GROUP BY DEPTNO
    )
);

SELECT D.DNAME, COUNT(E.EMPNO) AS CLRK_COUNT
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO
WHERE E.EJOB = 'CLRK'
GROUP BY D.DNAME;

SELECT ENAME
FROM EMPP
WHERE PRJ_ID IS NULL OR DEPTNO IS NULL;

CREATE VIEW EMP_PRI_VW AS
SELECT E.*, P.PRJ_NO, P.PRJ_NAME
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO
JOIN PROJECTS P ON E.DEPTNO = P.DNO AND E.PRJ_ID = P.PRJ_NO
WHERE D.DNAME = 'Marketing';

SELECT * FROM EMP_PRI_VW;

DESCRIBE EMP_PRI_VW;

SELECT ENAME, PRJ_NO, PRJ_NAME
FROM EMP_PRI_VW;

CREATE UNIQUE INDEX IDX_DEPTDNAME ON DEPTT(DNAME);

CREATE INDEX IDX_EMP_NAME_JOB ON EMPP(ENAME, EJOB);

CREATE SEQUENCE STUD_SEQ
START WITH 100
INCREMENT BY 3
MAXVALUE 999;

CREATE TABLE STUD (
    ROLLNO NUMBER PRIMARY KEY,
    NAME VARCHAR2(50)
);

INSERT INTO STUD (ROLLNO, NAME) 
VALUES (STUD_SEQ.NEXTVAL, 'John Doe');

INSERT INTO STUD (ROLLNO, NAME) 
VALUES (STUD_SEQ.NEXTVAL, 'Jane Smith');

SELECT *
FROM STUD;

CREATE SEQUENCE STUD_SEQ START WITH 100 INCREMENT BY 3 
MINVALUE 100 MAXVALUE 999;

CREATE TABLE STUD ( ROLL NUMBER(10), SNAME VARCHAR2(10) );

INSERT INTO STUD VALUES (STUD_SEQ.nextval,'SUMAN A');
INSERT INTO STUD VALUES (STUD_SEQ.nextval,'SUMAN B');

SELECT D.LOCATIONS, E.ENAME
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO
WHERE D.DNAME = 'Marketing'
UNION
SELECT D.LOCATIONS, E.ENAME
FROM EMPP E
JOIN DEPTT D ON E.DEPTNO = D.DNO
WHERE D.DNAME = 'Research';

SELECT DNO
FROM PROJECTS
WHERE PRJ_NO = 'P1'
INTERSECT
SELECT DNO
FROM PROJECTS
WHERE PRJ_NO = 'P3';











SELECT * 
FROM EMPP 
WHERE EMPNO NOT IN (SELECT DISTINCT MGR_ID FROM EMPP WHERE MGR_ID IS NOT NULL);

SELECT * 
FROM EMPP 
WHERE EMPNO NOT IN (SELECT MGR_ID FROM EMPP WHERE MGR_ID IS NOT NULL);

SELECT * 
FROM EMPP 
WHERE EMPNO IN (SELECT DISTINCT MGR_ID FROM EMPP);

SELECT
    EMPNO,
    ENAME,
    EJOB,
    MGR_ID,
    BIRTH_DATE,
    SAL,
    SAL * 1.20,
    COMM,
    DEPTNO,
    PRJ_ID,
    DATE_OF_JOIN
FROM
    EMPP; 
WHERE SAL * 1.20 > 30000;

SELECT ENAME, 
       SAL AS MONTHLY, 
       ROUND(SAL / 22, 2) AS DAILY, 
       ROUND(SAL / (22 * 8), 2) AS HOURLY 
FROM EMPP;

SELECT E.ENAME, D.DNAME, E.SAL, E.COMM 
FROM EMPP E 
JOIN DEPTT D ON E.DEPTNO = D.DNO 
WHERE E.SAL BETWEEN 20000 AND 50000 
  AND D.LOCATIONS = 'CHN';

SELECT E.ENAME 
FROM EMPP E 
JOIN EMPP M ON E.MGR_ID = M.EMPNO 
WHERE E.SAL > M.SAL;

SELECT E.ENAME 
FROM EMPP E 
JOIN EMPP M ON E.MGR_ID = M.EMPNO 
WHERE E.DEPTNO = M.DEPTNO;

SELECT ENAME 
FROM EMPP 
WHERE DEPTNO IN ('D1', 'D3') AND DATE_OF_JOIN < DATE '1982-12-31';

UPDATE EMPP 
SET SAL = SAL * 1.10 
WHERE COMM IS NULL OR COMM = 0;

SELECT ENAME, SAL 
FROM EMPP 
ORDER BY SAL DESC 
FETCH FIRST 3 ROWS ONLY;

SELECT E.ENAME, E.DEPTNO, E.SAL 
FROM EMPP E 
WHERE E.SAL = (SELECT MAX(SAL) FROM EMPP WHERE DEPTNO = E.DEPTNO);

SELECT DEPTNO, COUNT(*) AS EMP_COUNT 
FROM EMPP 
GROUP BY DEPTNO 
HAVING COUNT(*) > 3;

SELECT DNAME
FROM DEPTT
WHERE DNO = (
    SELECT DEPTNO
    FROM EMPP 
    GROUP BY DEPTNO 
    HAVING COUNT(*) >= 3
);

SELECT M.ENAME 
FROM EMPP M 
WHERE M.EMPNO IN (SELECT DISTINCT MGR_ID FROM EMP) AND M.SAL > (SELECT AVG(SAL) FROM EMP WHERE MGR_ID = M.EMPNO);

SELECT ENAME, SAL 
FROM EMPP 
WHERE MOD(SAL, 2) = 1;

SELECT ENAME 
FROM EMPP
WHERE COMM IS NULL OR COMM = 0;

SELECT ENAME, SAL 
FROM EMPP
WHERE SAL >= 100;

DELETE FROM EMPP
WHERE DATE_OF_JOIN < ADD_MONTHS(SYSDATE, -120);

SELECT E1.ENAME, E1.DATE_OF_JOIN 
FROM EMPP E1 
JOIN EMPP E2 ON E1.DATE_OF_JOIN = E2.DATE_OF_JOIN AND E1.EMPNO <> E2.EMPNO;

SELECT MGR_ID, COUNT(*) AS EMP_COUNT 
FROM EMPP 
WHERE MGR_ID IS NOT NULL 
GROUP BY MGR_ID 
ORDER BY EMP_COUNT DESC 
FETCH FIRST 1 ROW ONLY;












SELECT ENAME, SAL,
CASE
    WHEN SAL > 25000 THEN 'Just Salary'
    WHEN SAL = 25000 THEN 'On Target'
    ELSE 'Below Target'
END AS SALARY_STATUS
FROM EMPP;

-- Q2


SELECT MGR_ID, ENAME, SAL
FROM (
    SELECT MGR_ID, ENAME, SAL, MIN(SAL) OVER (PARTITION BY MGR_ID) AS MIN_SAL
    FROM EMPP
    WHERE MGR_ID IS NOT NULL
)
WHERE MIN_SAL >= 25000
ORDER BY SAL;

SELECT E.ENAME, E.DATE_OF_JOIN, M.DATE_OF_JOIN AS MANAGER_JOIN_DATE
FROM EMPP E
JOIN EMPP M ON E.MGR_ID = M.EMPNO
WHERE E.DATE_OF_JOIN < M.DATE_OF_JOIN;

SELECT 
    E.EMPNO, 
    E.ENAME,
    CASE 
        WHEN M.ENAME IS NULL THEN 'KING' 
        ELSE M.ENAME 
    END AS MANAGER_NAME,
    CASE 
        WHEN M.EMPNO IS NULL THEN 'N/A' 
        ELSE TO_CHAR(M.EMPNO)
    END AS MANAGER_NO
FROM EMPP E
LEFT JOIN EMPP M ON E.MGR_ID = M.EMPNO;

SELECT EJOB, ENAME, SAL
FROM (
    SELECT EJOB, ENAME, SAL, RANK() OVER (PARTITION BY EJOB ORDER BY SAL DESC) AS SAL_RANK
    FROM EMPP
)
WHERE SAL_RANK = 1
ORDER BY SAL DESC;

SELECT EJOB, ENAME, SAL
FROM (
    SELECT EJOB, ENAME, SAL, RANK() OVER (PARTITION BY EJOB ORDER BY SAL) AS SAL_RANK
    FROM EMPP
)
WHERE SAL_RANK = 1
ORDER BY SAL;

SELECT JOIN_YEAR, EMP_COUNT
FROM (
    SELECT 
        TO_CHAR(DATE_OF_JOIN, 'YYYY') AS JOIN_YEAR,
        COUNT(*) AS EMP_COUNT
    FROM EMPP
    GROUP BY TO_CHAR(DATE_OF_JOIN, 'YYYY'))
WHERE EMP_COUNT = (
    SELECT MAX(EMP_COUNT)
    FROM (
        SELECT COUNT(*) AS EMP_COUNT
        FROM EMPP
        GROUP BY TO_CHAR(DATE_OF_JOIN, 'YYYY'))
);

SELECT DEPTNO, ROUND(AVG(SAL), 2) AS AVG_SALARY
FROM EMPP
GROUP BY DEPTNO;

SELECT ENAME, SAL
FROM EMPP
WHERE SAL > (
    SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 'D30'
);

SELECT 
    UPPER(SUBSTR(ENAME, 1, CEIL(LENGTH(ENAME)/2))) ||
    LOWER(SUBSTR(ENAME, CEIL(LENGTH(ENAME)/2 + 1))) AS FORMATTED_NAME
FROM EMPP;

CREATE TABLE EMP_COPY AS
SELECT * FROM EMPP WHERE 1 = 0;

SELECT *
FROM EMPP
WHERE DEPTNO IN ('D1', 'D2')
ORDER BY ENAME;

SELECT EMPNO, ENAME, NVL(COMM, 0) AS COMM
FROM EMPP;

SELECT DEPTNO, EJOB, ROUND(AVG(SAL), 2) AS AVG_SALARY
FROM EMPP
GROUP BY DEPTNO, EJOB;

SELECT EJOB, AVG_SALARY
FROM (
    SELECT EJOB, AVG(SAL) AS AVG_SALARY
    FROM EMPP
    GROUP BY EJOB
)
WHERE AVG_SALARY = (
    SELECT MAX(AVG_SALARY)
    FROM (
        SELECT AVG(SAL) AS AVG_SALARY
        FROM EMPP
        GROUP BY EJOB
    )
);